theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title: https://kasini3000.github.io
paginate: 9
paginate_path: "page:num"

permalink: /:categories/:title/
include:
  - '_posts/**/*'
