theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title: https://kasini3000.github.io
paginate: 9
paginate_path: "page:num"

permalink: /:categories/:title/
navbar-links:
  主页: "https://zoharandroid.github.io"
  分类: "https://zoharandroid.github.io/categories/"
  标签: "https://zoharandroid.github.io/tags/"
  项目:
    - Learn markdown: "http://www.markdowntutorial.com/"
  关于我: "aboutme"
  搜索: "search"
