theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title: https://kasini3000.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kasini3000.github.io" # the base hostname & protocol for your site
permalink: /:categories/:year/:month/:day/:title